set_mode:
  fields:
    monitor_id:
      required: true
      example: "TAPOTEST01"
      selector:
        text:
    mode:
      required: true
      example: "record"
      selector:
        select:
          options:
            - "start"
            - "record"
            - "stop"
            - "idle"

trigger_motion:
  fields:
    monitor_id:
      required: true
      example: "TAPOTEST01"
      selector:
        text:

ptz:
  fields:
    monitor_id:
      required: true
      example: "TAPOTEST01"
      selector:
        text:
    direction:
      required: true
      example: "left"
      selector:
        select:
          options:
            - "up"
            - "down"
            - "left"
            - "right"
            - "zoom_in"
            - "zoom_out"
            - "center"
            - "stopMove"
            - "setHome"
